apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.1.10"],"port":80,"protocol":"HTTP","serviceName":"rook-ceph:rook-ceph-mgr-dashboard","ingressName":"rook-ceph:ceph","hostname":"ceph.qlongit.cn","path":"/","allNodes":true}]'
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: ceph
  namespace: rook-ceph
spec:
  defaultBackend:
    service:
      name: rook-ceph-mgr-dashboard
      port:
        number: 8443
  rules:
    - host: ceph.qlongit.cn
      http:
        paths:
          - backend:
              service:
                name: rook-ceph-mgr-dashboard
                port:
                  number: 8443
            path: /
            pathType: Prefix
